import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import ScrollEffects from "@/components/ScrollEffects";

export const metadata = {
  title: "Privacy Policy - Pipi Tabs",
  description: "Privacy Policy for Pipi Tabs extension.",
};

export default function PrivacyPage() {
  return (
    <>
      <ScrollEffects />
      <Nav />
      <main className="max-w-4xl mx-auto px-6 pt-32 pb-20 fade-up">
        <h1 className="text-4xl md:text-5xl font-bold mb-4 dark:text-white">Privacy Policy</h1>
        <p className="text-gray-500 dark:text-gray-400 mb-12">Last Updated: 2026-08-19</p>

        <section className="space-y-8">
          <div>
            <h2 className="text-2xl font-semibold mb-4 dark:text-white">Introduction</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              Pipi (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) is committed to protecting your privacy. This
              Privacy Policy explains how we collect, use, and safeguard your information when you use our Chrome
              extension, Pipi, and its companion website.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 dark:text-white">Information We Collect</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
              Pipi is designed to help you manage and organize your bookmarks for research projects. To provide this
              service, we process the following data:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-600 dark:text-gray-300">
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Bookmark Data:</strong> The URLs and titles of
                the websites you choose to save.
              </li>
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Project/Group Names:</strong> The names of the
                folders or projects you create to organize your bookmarks.
              </li>
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Account Data:</strong> If you choose to sign in,
                your email address and, for password sign-in, a username — used to sync your data across devices.
              </li>
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Usage Data:</strong> Preferences and settings you
                configure within the extension.
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 dark:text-white">How We Use Your Information</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
              We use the information we collect solely for the purpose of providing the extension&apos;s
              functionality:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-600 dark:text-gray-300">
              <li>To save and retrieve your bookmarks.</li>
              <li>To organize bookmarks into the research project groups you define.</li>
              <li>To display your saved content within the extension interface.</li>
              <li>To authenticate you and sync your data across your signed-in devices.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 dark:text-white">Data Storage and Security</h2>
            <ul className="list-disc pl-6 space-y-2 text-gray-600 dark:text-gray-300">
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Local &amp; Synced Storage:</strong> Data
                generated by Pipi (bookmarks, groups, settings) is stored locally on your device using the Chrome
                Storage API, and — if you sign in — securely synced via our backend (Convex) so it is available across
                your devices.
              </li>
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Authentication:</strong> Sign-in happens on our
                website (not inside the extension) via Google OAuth or email/password, and a signed token is passed
                back to the extension to authenticate future requests.
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 dark:text-white">Permissions Usage</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
              Pipi requires specific permissions to function correctly. Here is how each is used:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-600 dark:text-gray-300">
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Storage:</strong> Used to save your bookmarks,
                project groups, and preferences locally on your device.
              </li>
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Tabs:</strong> Used to access the URL and title of
                the active tab when you initiate a &quot;save&quot; action, and to open your saved bookmarks.
              </li>
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Alarms:</strong> Used to schedule internal
                background tasks to maintain extension performance.
              </li>
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Notifications:</strong> Used to provide visual
                feedback, such as confirming a bookmark has been successfully saved.
              </li>
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Offscreen:</strong> Used to perform background
                processing (such as data handling) without opening a visible window.
              </li>
              <li>
                <strong className="text-gray-800 dark:text-gray-100">Host Permissions (All URLs):</strong> Required to
                interact with the websites you visit, enabling the extension to capture the URL and title for
                bookmarking purposes from any page.
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 dark:text-white">Third-Party Services</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              Pipi does not share your data with third-party advertisers. We use Convex for backend data storage and
              authentication, and Google Sign-In as an optional authentication method.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 dark:text-white">Changes to This Privacy Policy</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
              Privacy Policy on this page.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4 dark:text-white">Contact Us</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              If you have any questions about this Privacy Policy, please contact us at:{" "}
              <a href="mailto:akpanjoseph2021@gmail.com" className="text-blue-600 dark:text-blue-400 hover:underline">
                akpanjoseph2021@gmail.com
              </a>
            </p>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
