// Handoff protocol between this website and the Pipi extension.
//
// The extension opens `/auth?source=extension&extensionId=<id>&nonce=<n>`
// in a normal tab. Once sign-in completes here, we send the resulting JWT
// back to the extension via chrome.runtime.sendMessage (requires the
// extension to list this site's origin in manifest.json's
// externally_connectable.matches). The nonce is generated by the extension
// per sign-in attempt and echoed back so the extension can reject stale or
// replayed handoffs.
//
// We intentionally do NOT ship a refresh token to the extension: refresh
// tokens would need to live indefinitely in chrome.storage.local, widening
// the blast radius of a compromised extension. Instead, when the extension's
// stored JWT expires, it silently reopens this page (source=extension,
// silent=1); if this site's own Convex Auth session is still valid, a fresh
// JWT is handed off with no user interaction. If not, the normal sign-in
// form is shown.

export interface ExtensionHandoffParams {
  source: "extension" | null;
  extensionId: string | null;
  nonce: string | null;
  silent: boolean;
}

export function parseHandoffParams(searchParams: URLSearchParams): ExtensionHandoffParams {
  return {
    source: searchParams.get("source") === "extension" ? "extension" : null,
    extensionId: searchParams.get("extensionId"),
    nonce: searchParams.get("nonce"),
    silent: searchParams.get("silent") === "1",
  };
}

function allowedExtensionIds(): string[] {
  return (process.env.NEXT_PUBLIC_EXTENSION_IDS || "")
    .split(",")
    .map((id) => id.trim())
    .filter(Boolean);
}

export function isAllowedExtensionId(extensionId: string | null): extensionId is string {
  if (!extensionId) return false;
  return allowedExtensionIds().includes(extensionId);
}

export interface HandoffMessage {
  type: "PIPI_AUTH_TOKEN";
  nonce: string;
  token: string;
}

export interface HandoffResponse {
  ok: boolean;
  error?: string;
}

/** Sends the JWT to the extension. Resolves once the extension acks (or rejects on error/timeout). */
export function sendTokenToExtension(extensionId: string, nonce: string, token: string): Promise<HandoffResponse> {
  return new Promise((resolve, reject) => {
    const runtime = typeof chrome === "undefined" ? undefined : chrome.runtime;
    if (!runtime?.sendMessage) {
      reject(new Error("chrome.runtime is not available in this browser context."));
      return;
    }

    const message: HandoffMessage = { type: "PIPI_AUTH_TOKEN", nonce, token };
    const timeout = setTimeout(() => reject(new Error("Timed out waiting for the extension to respond.")), 8000);

    runtime.sendMessage(extensionId, message, (response: HandoffResponse | undefined) => {
      clearTimeout(timeout);
      if (runtime.lastError) {
        reject(new Error(runtime.lastError.message));
        return;
      }
      resolve(response ?? { ok: false, error: "No response from extension." });
    });
  });
}
